# api-related fields
api:
  # The port on which the API will be exposed (default:3001)
  port: 3001

  # Enable/disable development CORS
  dev-cors: true

  # Allowed hosts for HTTP API development CORS
  dev-cors-host: "*"

# Dashboard-related fields
dashboard:
  # The port on which the Dashboard will be exposed (default:3000)
  # WARNING: it must not be the same as api.port!
  port: 3000

  config-management:
    enabled: true

# database fields
db:
  # Database host
  host: "barnbridge-postgres"

  # Database port
  port: 5432

  # Database sslmode
  sslmode: "disable"

  # Database name
  dbname: "barnbridge"

  # Database user (also allowed via PG_USER env var)
  user: "barnbridge"

# ethereum-related fields
eth:
  client:
    # HTTP endpoint of a web3-compatible node (mandatory)
    http: "http://localhost:8545"

    # Websockets endpoint of JSON-RPC enabled node (optional)
    # if this is present, the task manager will use a newHeads subscription to watch for new blocks
    # if not present, the task manager will use polling to get the highest block
    ws: "ws://localhost:8546"

    # The interval at which the task manager will poll the node for best block (default:"15s")
    # optional, only used if `ws` url is not specified
    poll-interval: "15s"

# feature flags
feature:
  # Backfilling
  backfill:
    # Enable/disable the backfilling feature
    enabled: false

  # Lag feature
  lag:
    # Enable/disable the lag feature
    enabled: true

    # The amount of blocks to lag behind the tip of the chain if the lag feature is enabled
    value: 10

  # Automatic migrations
  automigrate:
    # Enable/disable the automatic migrations
    enabled: true

  #slack notify service
  slack:
      webhook: ""

# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=info"

# redis-related fields
redis:
  # URL of redis server (default:"localhost:6379")
  server: "barnbridge-redis:6379"

  # The name of the redis list the scraper will use for task management (default: "todo")
  list: "todo"

abi-path: "./abis"

storable:
  bond:
    address: "0x0391D2021f89DC339F60Fff84546EA23E337750f"
  barn:
    address: "0x10e138877df69Ca44Fdc68655f86c88CDe142D7F"
  governance:
    address: "0x4cAE362D7F227e3d306f70ce4878E245563F3069"
  yieldFarming:
    address : "0xb0fa2beee3cf36a7ac7e99b885b48538ab364853"
  smartYieldState:
    compound-comptroller: "0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b"
    blocks-per-minute: 4
  smartYieldRewards:
    pool-factory-address: "0x2e93403C675Ccb9C564edf2dC6001233d0650582"

